version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: greetings_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: greetings_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Python Flask Application
  web:
    build: .
    container_name: greetings_app
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=greetings_db
      - FLASK_ENV=development
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app_network
    volumes:
      - ./templates:/app/templates:ro

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local